version: '3.8'

services:
  urlshortener:
    build: .
    container_name: urlshortener
    ports:
      - "8080:8080"
    depends_on:
      postgres:
          condition: service_healthy
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: